Repository hi-METAVIRTUAL/Bloom, pull requests merged in 2023-10, with the labels that each got.

#227 탈퇴 회원 로그인 불가 + 상담 예약 여부에 따라 view 달라짐
  src/main/java/com/metavirtual/bloom/configuration/MainController.java
  src/main/java/com/metavirtual/bloom/user/controller/UserController.java
  src/main/java/com/metavirtual/bloom/user/model/service/UserServiceImpl.java
  src/main/resources/mappers/user/UserMapper.xml
  src/main/resources/static/js/registMemberEvent.js
  src/main/resources/templates/components/Header.html
  src/main/resources/templates/index.html
  src/main/resources/templates/user/bookingStat.html
  src/main/resources/templates/user/memberRegist.html
Labels: documentation, enhancement

#234 예약 기능 구현
  src/main/java/com/metavirtual/bloom/booking/controller/BookingController.java
  src/main/java/com/metavirtual/bloom/booking/model/dao/BookingMapper.java
  src/main/java/com/metavirtual/bloom/booking/model/service/BookingService.java
  src/main/java/com/metavirtual/bloom/match/controller/MatchController.java
  src/main/java/com/metavirtual/bloom/user/model/service/UserServiceImpl.java
  src/main/resources/application.yml
  src/main/resources/mappers/psychometry/MatchMapper.xml
  src/main/resources/templates/booking/reservation.html
  src/main/resources/templates/index.html
  src/main/resources/templates/mypage/therapist/therapistInfo.html
  src/main/resources/templates/psychological/match/introduceTherapy.html
  src/main/resources/templates/psychological/match/therapyList.html
Labels: documentation, enhancement

#238 관리자페이지 고객센터 탭 완성, 회원관리 탭 중 상세조회 미완
  src/main/java/com/metavirtual/bloom/common/paging/AdminCriteria.java
  src/main/java/com/metavirtual/bloom/common/paging/Paging.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/controller/AdminPageController.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dao/AdminPageMapper.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dto/AdminCommentDTO.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dto/CsDetailDTO.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dto/CsListDTO.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dto/TherapistList.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/service/AdminPageService.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/service/AdminPageServiceImpl.java
  src/main/resources/mappers/MyPage/AdminPageMapper.xml
  src/main/resources/templates/mypage/admin/csAnswer.html
  src/main/resources/templates/mypage/admin/customerService.html
  src/main/resources/templates/mypage/admin/inquireMember.html
  src/main/resources/templates/mypage/admin/inquireTherapist.html
  src/main/resources/templates/mypage/admin/reservePopup.html
  src/main/resources/templates/mypage/admin/therapistProfile.html
Labels: enhancement

#239 예약
  Bloom DDL5.txt
  src/main/java/com/metavirtual/bloom/booking/controller/BookingController.java
  src/main/java/com/metavirtual/bloom/booking/model/service/BookingService.java
  src/main/java/com/metavirtual/bloom/configuration/SecurityConfiguration.java
  src/main/java/com/metavirtual/bloom/match/controller/MatchController.java
  src/main/java/com/metavirtual/bloom/user/model/dto/MemberDTO.java
  src/main/java/com/metavirtual/bloom/user/model/service/UserServiceImpl.java
  src/main/resources/mappers/booking/BookingMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
  src/main/resources/static/css/reservation/calendar.css
  src/main/resources/templates/booking/reservation.html
  src/main/resources/templates/index.html
  src/main/resources/templates/psychological/match/introduceTherapy.html
  src/main/resources/templates/psychological/match/therapyList.html
  src/main/resources/templates/user/login.html
  src/main/resources/templates/user/memberRegist.html
  src/main/resources/templates/user/memberRegistSuccess.html
  src/main/resources/templates/user/therapistRegist.html
  src/main/resources/templates/user/therapistRegistSuccess.html
  src/main/resources/templates/user/verificationIdSent.html
  src/main/resources/templates/user/verificationPasswordSent.html
Labels: bug, documentation, enhancement

#241 관리자페이지 회원 상세 조회
  src/main/java/com/metavirtual/bloom/myPage/adminPage/controller/AdminPageController.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dao/AdminPageMapper.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dto/MemberReport.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/dto/TherapistComment.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/service/AdminPageService.java
  src/main/java/com/metavirtual/bloom/myPage/adminPage/model/service/AdminPageServiceImpl.java
  src/main/java/com/metavirtual/bloom/myPage/memberPage/model/dto/MemberInfo.java
  src/main/resources/mappers/MyPage/AdminPageMapper.xml
  src/main/resources/mappers/MyPage/MemberPageMapper.xml
  src/main/resources/templates/mypage/admin/customerService.html
  src/main/resources/templates/mypage/admin/editMemberInfo.html
  src/main/resources/templates/mypage/admin/editTherapistInfo.html
  src/main/resources/templates/mypage/admin/inquireMember.html
  src/main/resources/templates/mypage/admin/inquireTherapist.html
  src/main/resources/templates/mypage/member/memberInfo.html
  src/main/resources/templates/mypage/member/postList.html
Labels: enhancement

#242 예약
  src/main/resources/templates/booking/reservation.html
Labels: enhancement
